/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.2 at Mon Mar  9 23:33:14 2015. */

#ifndef PB_GPI_PB_H_INCLUDED
#define PB_GPI_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _GPIData_MessageType {
    GPIData_MessageType_GEAR = 1,
    GPIData_MessageType_CUTOFF = 2,
    GPIData_MessageType_REQUEST = 3
} GPIData_MessageType;

typedef enum _RequestMessage_RequestType {
    RequestMessage_RequestType_GET_CUTOFFS = 1
} RequestMessage_RequestType;

/* Struct definitions */
typedef struct _CutOffMessage {
    bool has_firstCutoff;
    int32_t firstCutoff;
    bool has_secondCutoff;
    int32_t secondCutoff;
    bool has_thirdCutoff;
    int32_t thirdCutoff;
    bool has_fourthCutoff;
    int32_t fourthCutoff;
    bool has_fifthCutoff;
    int32_t fifthCutoff;
    bool has_sixthCutoff;
    int32_t sixthCutoff;
} CutOffMessage;

typedef struct _GearMessage {
    bool has_gear;
    int32_t gear;
} GearMessage;

typedef struct _RequestMessage {
    RequestMessage_RequestType type;
} RequestMessage;

typedef struct _GPIData {
    GPIData_MessageType type;
    bool has_gearMessage;
    GearMessage gearMessage;
    bool has_cutOffMessage;
    CutOffMessage cutOffMessage;
    bool has_requestMessage;
    RequestMessage requestMessage;
} GPIData;

/* Default values for struct fields */

/* Initializer values for message structs */
#define GPIData_init_default                     {(GPIData_MessageType)0, false, GearMessage_init_default, false, CutOffMessage_init_default, false, RequestMessage_init_default}
#define GearMessage_init_default                 {false, 0}
#define CutOffMessage_init_default               {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define RequestMessage_init_default              {(RequestMessage_RequestType)0}
#define GPIData_init_zero                        {(GPIData_MessageType)0, false, GearMessage_init_zero, false, CutOffMessage_init_zero, false, RequestMessage_init_zero}
#define GearMessage_init_zero                    {false, 0}
#define CutOffMessage_init_zero                  {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define RequestMessage_init_zero                 {(RequestMessage_RequestType)0}

/* Field tags (for use in manual encoding/decoding) */
#define CutOffMessage_firstCutoff_tag            1
#define CutOffMessage_secondCutoff_tag           2
#define CutOffMessage_thirdCutoff_tag            3
#define CutOffMessage_fourthCutoff_tag           4
#define CutOffMessage_fifthCutoff_tag            5
#define CutOffMessage_sixthCutoff_tag            6
#define GearMessage_gear_tag                     1
#define RequestMessage_type_tag                  1
#define GPIData_type_tag                         1
#define GPIData_gearMessage_tag                  2
#define GPIData_cutOffMessage_tag                3
#define GPIData_requestMessage_tag               4

/* Struct field encoding specification for nanopb */
extern const pb_field_t GPIData_fields[5];
extern const pb_field_t GearMessage_fields[2];
extern const pb_field_t CutOffMessage_fields[7];
extern const pb_field_t RequestMessage_fields[2];

/* Maximum encoded size of messages (where known) */
#define GPIData_size                             95
#define GearMessage_size                         11
#define CutOffMessage_size                       66
#define RequestMessage_size                      6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
